<!DOCTYPE html>
<html lang="en"><head>
<script src="03_classification_files/libs/clipboard/clipboard.min.js"></script>
<script src="03_classification_files/libs/quarto-html/tabby.min.js"></script>
<script src="03_classification_files/libs/quarto-html/popper.min.js"></script>
<script src="03_classification_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="03_classification_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="03_classification_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="03_classification_files/libs/quarto-html/quarto-syntax-highlighting-9ea0a49c779b6fc496fdb60b6bf00fef.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">
<title>classification</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
<link rel="stylesheet" href="03_classification_files/libs/revealjs/dist/reset.css">
<link rel="stylesheet" href="03_classification_files/libs/revealjs/dist/reveal.css">
<style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #657b83; background-color: #fdf6e3; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #657b83; } /* Normal */
    code span.al { color: #d33682; font-weight: bold; } /* Alert */
    code span.an { color: #268bd2; } /* Annotation */
    code span.at { color: #268bd2; } /* Attribute */
    code span.bn { color: #2aa198; } /* BaseN */
    code span.bu { color: #cb4b16; } /* BuiltIn */
    code span.cf { color: #859900; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #2aa198; } /* Char */
    code span.cn { color: #2aa198; font-weight: bold; } /* Constant */
    code span.co { color: #93a1a1; font-style: italic; } /* Comment */
    code span.cv { color: #2aa198; } /* CommentVar */
    code span.do { color: #dc322f; } /* Documentation */
    code span.dt { color: #b58900; font-weight: bold; } /* DataType */
    code span.dv { color: #2aa198; } /* DecVal */
    code span.er { color: #dc322f; text-decoration: underline; } /* Error */
    code span.ex { color: #268bd2; font-weight: bold; } /* Extension */
    code span.fl { color: #2aa198; } /* Float */
    code span.fu { color: #268bd2; } /* Function */
    code span.im { color: #2aa198; } /* Import */
    code span.in { color: #b58900; } /* Information */
    code span.kw { color: #859900; font-weight: bold; } /* Keyword */
    code span.op { color: #859900; } /* Operator */
    code span.ot { color: #859900; } /* Other */
    code span.pp { color: #cb4b16; } /* Preprocessor */
    code span.re { color: #268bd2; background-color: #eee8d5; } /* RegionMarker */
    code span.sc { color: #dc322f; } /* SpecialChar */
    code span.ss { color: #dc322f; } /* SpecialString */
    code span.st { color: #2aa198; } /* String */
    code span.va { color: #268bd2; } /* Variable */
    code span.vs { color: #2aa198; } /* VerbatimString */
    code span.wa { color: #cb4b16; } /* Warning */
  </style>
<link rel="stylesheet" href="03_classification_files/libs/revealjs/dist/theme/quarto-61b8fe8fdb637f5238075e4cdce2e752.css">
<link href="03_classification_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
<link href="03_classification_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
<link href="03_classification_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
<link href="03_classification_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
<style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section><section id="classifiers" class="title-slide slide level1 center" data-background-color="#447099"><h1>3. Classifiers</h1>
<h2>
Big data in Economics
</h2>
<h3>
Juan D. Montoro-Pons | 2024/25
</h3>
</section><section class="slide level2">
<img data-src="pics/machine_learning_captcha_2x.png" class="quarto-figure quarto-figure-center r-stretch"></section><section id="classification-problems" class="slide level2" style="color:#447099"><h2>Classification problems</h2>
<p>&nbsp;</p>
<ul>
<li><p>Classification problems: qualitative/categorical response</p></li>
<li><p>Classification techniques or classifiers</p></li>
<li><p>Concepts used in regression also apply: supervised learning, data partitioning, underfitting, overfitting, among others</p></li>
<li>
<p>Why not linear regression in classification problems?</p>
<ul>
<li>For binary problems <span class="math inline">\(X\hat{\beta}\)</span> is an estimate of <span class="math inline">\(P(Y=1|X)\)</span>
</li>
<li>Inability to produce meaningful estimates for <span class="math inline">\(P(Y|X)\)</span> (are not forced to be inside the <span class="math inline">\([0,1]\)</span> interval)</li>
<li>Impossibility to adequately accomodate qualitative responses with more than two classes (response should have implicit ordering and even then the difference between levels of the variable is arbitrary)</li>
</ul>
</li>
</ul>
<aside class="notes"><p>While we could estimate the probability using a linear model it must be said that it violates two assumptions: normality of the residuals (they will not be) and homoskedasticity (variance will depend on <span class="math inline">\(X\)</span>).</p>
<p>In the more than 2 categories we can think of a categorical variable that defines a credit situation wrt a financial institution: current, delinquent (late), and in default. We could code the categories as Y=1,2,3 (here there is an implicit ordering) BUT does the gap between current and delinquent equals that between delinquent and default? Probably not. More problematic is the case of a categorical variables in which there is no inherent ordering.</p>
<p>For definitions on credit status: https://www.investopedia.com/ask/answers/062315/what-are-differences-between-delinquency-and-default.asp</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside></section><section id="regression-the-binary-response-case" class="slide level2" style="color:#447099"><h2>Regression: the binary response case</h2>
<p>&nbsp;</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-1-1">The setup</a></li>
<li><a href="#tabset-1-2">The data</a></li>
<li><a href="#tabset-1-3">Predicting the response</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>&nbsp;</p>
<p>GOAL: predict the probability of a customer defaulting on a loan.</p>
<ul>
<li>Outcome: Default (binary)</li>
<li>Two predictors are used: Loan amount and term of loan (both are standardized).</li>
</ul>
</div>
<div id="tabset-1-2">
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="03_classification_files/figure-revealjs/unnamed-chunk-3-1.png" width="1152"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-3">
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="03_classification_files/figure-revealjs/unnamed-chunk-4-3.png" width="1152"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="logistic-regression" class="slide level2" style="color:#447099"><h2>Logistic regression</h2>
<p>&nbsp;</p>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-2-1">The linear model</a></li>
<li><a href="#tabset-2-2">Logistic regression in <code>Python</code></a></li>
<li><a href="#tabset-2-3">Decision boundary</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb1-2"><a href=""></a>lm <span class="op">=</span> LinearRegression()</span>
<span id="cb1-3"><a href=""></a>lm.fit(X_train,y_train)<span class="op">;</span></span>
<span id="cb1-4"><a href=""></a>lm.intercept_, lm.coef_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(0.5083285752419477, array([0.25246833, 0.00035319]))</code></pre>
</div>
</div>
<p>The central output of a linear regression is a predictor for the conditional mean:</p>
<p><span class="math display">\[\mu_i=0.5083285752419477 +0.25246833 \times \textrm{loan_amount} + 0.00035319 \times \textrm{term}\]</span></p>
</div>
<div id="tabset-2-2">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb3-2"><a href=""></a>logistic <span class="op">=</span> LogisticRegression()</span>
<span id="cb3-3"><a href=""></a>logistic.fit(X_train,y_train)<span class="op">;</span></span>
<span id="cb3-4"><a href=""></a>logistic.intercept_, logistic.coef_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(array([-0.0391638]), array([[2.03475556, 0.10518903]]))</code></pre>
</div>
</div>
<p>The central output of a logistic regression is a linear predictor (we call it <span class="math inline">\(\nu_i\)</span>)</p>
<p><span class="math display">\[\nu_i=-0.0391638 +2.03475556 \times \textrm{loan_amount} + 0.10518903 \times \textrm{term}\]</span> The linear predictor is transformed to generate predictions on the probability of default <span class="math inline">\(\mu_i\)</span>. The logit link is used:</p>
<p><span class="math display">\[\log\left(\frac{\mu_i}{1-\mu_i}\right) =-0.0391638 +2.03475556 \times \textrm{loan_amount} + 0.10518903 \times \textrm{term}\]</span></p>
<p>Solving for <span class="math inline">\(\mu_i\)</span> we get predicted probabilities for given <span class="math inline">\(x_i\)</span> values:</p>
<p><span class="math display">\[\mu_i=\frac{\exp\left(-0.0391638 +2.03475556 \times \textrm{loan_amount} + 0.10518903 \times \textrm{term}\right)}{1+\exp\left(-0.0391638 +2.03475556 \times \textrm{loan_amount} + 0.10518903 \times \textrm{term}\right)}\]</span></p>
</div>
<div id="tabset-2-3">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="03_classification_files/figure-revealjs/unnamed-chunk-7-5.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section></section><section><section id="generalised-linear-models-glms" class="title-slide slide level1 center" data-background-color="#447099"><h1>Generalised linear models (GLMs)</h1>

</section><section id="components-of-a-glm" class="slide level2 scrollable" style="color:#447099"><h2>Components of a GLM</h2>
<p>&nbsp;</p>
<ol type="1">
<li><p>A <strong>stochastic component</strong> that specifies the probability distribution of the reponse variable (EDM family. e.g., normal, binomial, poisson)</p></li>
<li><p>A <strong>systematic component</strong> or linear predictor: <span class="math display">\[\nu_i = \beta_1 + \beta_2 x_{2i} +\ldots + \beta_p x_{pi}\]</span></p></li>
<li><p><strong>Link function</strong>, that is, a functional form that connects the mean of the response with the systematic component (the linear predictor): <span class="math display">\[g(\mu_i)=\nu_i \]</span></p></li>
</ol>
<blockquote>
<p>Because GLMs assume a specific probability distribution for the responses from the EDM family, (numerical) maximum likelihood estimation procedures can be used for parameter estimation: <span class="math inline">\(-l(\beta|x,y)\)</span> is the loss function to be minimized</p>
</blockquote>
</section><section id="the-linear-model-1" class="slide level2 scrollable" style="color:#447099"><h2>The linear model</h2>
<p>&nbsp;</p>
<ol type="1">
<li><p><strong>Gaussian distribution for the response</strong> <span class="math inline">\(y_i\)</span>: <span class="math display">\[y_i \sim N(\mu_i, \sigma^2)\]</span></p></li>
<li><p><strong>Linear predictor</strong>: <span class="math display">\[\nu_i = \beta_1 + \beta_2 x_{2i} + \ldots + \beta_p x_{pi}\]</span></p></li>
<li><p><strong>Identity link function:</strong> <span class="math inline">\(\nu_i=\mu_i\)</span></p></li>
</ol>
<p>The linear model estimates the conditional mean of the response variable based on the linear predictor.</p>
<p><span class="math display">\[E[y|X]=\beta_1 + \beta_2 x_{2i} + \ldots + \beta_p x_{pi}\]</span></p>
</section><section id="binary-responses-the-logistic-model" class="slide level2 scrollable" style="color:#447099"><h2>Binary responses: the logistic model</h2>
<p>Let a binary outcome <span class="math inline">\(y \in \{0,1\}\)</span> and <span class="math inline">\(x_1,x_2\ldots x_p\)</span> features. In this case</p>
<ol type="1">
<li><p>The <strong>stochastic component</strong> (Bernouilli distribution): <span class="math display">\[P(y_i;\mu_i) =\mu_i ^{y}(1-\mu_i )^{(1-y_i)}\]</span></p></li>
<li><p>The <strong>linear predictor</strong>: <span class="math display">\[\nu_i = \beta_1 + \beta_2 x_{2i} +\ldots  +\beta_p x_{pi}\]</span></p></li>
<li><p>The <strong>link function</strong>: <span class="math display">\[\nu_i=g(\mu_i)=log\left(\frac{\mu_i}{1-\mu_i}\right)\]</span></p></li>
</ol>
<p>Combining these elements the logit model predicts the conditional mean of the response as:</p>
<p><span class="math display">\[P(y_i=1|X)=\mu_i=\frac{\exp{X\beta}}{1+\exp{X\beta}}\]</span></p>
</section><section id="multiclass-regression-the-multinomial-logistic-model" class="slide level2 scrollable" style="color:#447099"><h2>Multiclass regression: the multinomial logistic model</h2>
<p>&nbsp;</p>
<p>If the response <span class="math inline">\(y\)</span> has <span class="math inline">\(k&gt;2\)</span> classes we use a multinomial model, also a GLM. Its components:</p>
<ol type="1">
<li><p><strong>Stochastic component</strong>: response follows a multinomial model, i.e., it can take on one of <span class="math inline">\(k\)</span> categories. The probability there are <span class="math inline">\(y_1,y_2\ldots y_k\)</span> outcomes in each category <span class="math inline">\(i=\ldots k\)</span> of the response <span class="math inline">\(y\)</span> in <span class="math inline">\(n\)</span> trials is given by <span class="math display">\[
P(y_1, y_2, \ldots, y_k) = \frac{n!}{y_1! y_2! \cdots y_k!} p_1^{y_1} p_2^{y_2} \cdots p_k^{y_k}
\]</span></p></li>
<li><p>One <strong>linear predictor</strong> for each <span class="math inline">\(j\)</span>-th category (where <span class="math inline">\(j = 1, 2, \ldots, k-1\)</span>): is <span class="math display">\[
\nu_j = \beta_{0j} + \beta_{1j} x_1 + \beta_{2j} x_2 + \cdots + \beta_{pj} x_p
\]</span></p></li>
<li><p>A logit <strong>link function</strong>. For the <span class="math inline">\(j\)</span>-th category is: <span class="math display">\[
\log \left(\frac{P(Y = j)}{P(Y = k)}\right) = \nu_j
\]</span> where <span class="math inline">\(P(Y = j)\)</span> is the probability of the <span class="math inline">\(j\)</span>-th category, and <span class="math inline">\(P(Y = k)\)</span> is the probability of the reference category (can be chosen arbitrarily).</p></li>
</ol></section><section id="multinomial-logistic-regression" class="slide level2" style="color:#447099"><h2>Multinomial logistic regression</h2>
<p>&nbsp;</p>
<p>The conditional mean is given by:</p>
<p><span class="math display">\[P(y=m|X)=\frac{\exp{(X\beta_m)}}{\sum_j \exp{(X\beta_j)}}\]</span></p>
<ul>
<li><p>Conceptually this would be <em>like</em> estimating <span class="math inline">\(m-1\)</span> binary logit models.</p></li>
<li><p>To ensure identificability the coefficients of one category are fixed. I.e. one sets <span class="math inline">\(\beta=0\)</span> for a given <em>baseline</em> or <em>reference</em> category.</p></li>
<li><p>The choice of baseline is arbitrary (although some might favor the most frequent class or make the choice based on theoretical considerations)</p></li>
<li><p>To train a multinomial model in <code>Python</code> use <code>LogisticRegression(multi_class='multinomial')</code></p></li>
</ul></section><section id="other-glms" class="slide level2 scrollable" style="color:#447099"><h2>Other GLMs</h2>
<p>Count data can be modeled using the Poisson (mean equals variance) and Negative binomial (overdispersion) specifications. In the former:</p>
<ol type="1">
<li><p><strong>Stochastic component</strong>: response follows a Poisson model, <span class="math display">\[
P(y_i|\lambda) = \frac{\exp({-\lambda})\, \lambda^{y_i}}{y_i!}
\]</span></p></li>
<li><p>The <strong>linear predictor</strong> is: <span class="math display">\[
\nu_j = \beta_{0} + \beta_{1} x_1 + \beta_{2} x_2 + \cdots + \beta_{p} x_p
\]</span></p></li>
<li><p>A logarithmic <strong>link function</strong> that ensures that counts will always be non-negative <span class="math display">\[
\log (\lambda)  = X \beta
\]</span> Note that the latter implies</p></li>
</ol>
<p><span class="math display">\[E[y|X]=\lambda=\exp({X\beta})\]</span></p>
<blockquote>
<p>Other GLMs include non-negative responses or survival times</p>
</blockquote>
</section></section><section><section id="regularized-glms" class="title-slide slide level1 center" data-background-color="#447099"><h1>Regularized GLMs</h1>

</section><section id="regularized-glms-1" class="slide level2" style="color:#447099"><h2>Regularized GLMs</h2>
<p>&nbsp;</p>
<ul>
<li><p>Regularization is used to avoid <em>overfitting</em> when training GLMs for predictive purposes</p></li>
<li><p>We use the same approach as with the linear model: a penalty terms is introduced in the loss function to that penalizes the magnitude of the estimated coefficients</p></li>
<li><p>There is a tuning parameter <span class="math inline">\(\lambda\)</span> that controls for the amount of regularization.</p></li>
<li><p>The optimal value for <span class="math inline">\(\lambda\)</span> is chosen using resampling (cross-validation)</p></li>
</ul>
<p>The loss function of a regularized GLM includes a regularizer <span class="math inline">\(R\)</span>: <span class="math display">\[-l(\beta|x,y)+\lambda R(\beta)\]</span></p>
</section><section id="penalized-parametric-regression-models" class="slide level2 scrollable" style="color:#447099"><h2>Penalized parametric regression models</h2>
<p>&nbsp;</p>
<p>As in the case of the linear model, the penalty can be <span class="math inline">\(L_1\)</span> or <span class="math inline">\(L_2\)</span> or a combination of the two:</p>
<ol type="1">
<li>LASSO: <span class="math display">\[R(\beta)=||\beta||_1=\sum_j|\beta_j|\]</span>
</li>
<li>Ridge: <span class="math display">\[R(\beta)=||\beta||_2=\sum_j\beta_j^2\]</span>
</li>
<li>Elastic net: <span class="math display">\[R(\beta)=\alpha ||\beta||_1+ \frac{1}{2}(1-\alpha)||\beta||_2\]</span>
</li>
</ol></section><section id="penalized-parametric-regression-models-1" class="slide level2" style="color:#447099"><h2>Penalized parametric regression models</h2>
<p>&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href=""></a></span>
<span id="cb5-2"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegressionCV</span>
<span id="cb5-3"><a href=""></a>lasso_logit <span class="op">=</span> LogisticRegressionCV(Cs<span class="op">=</span><span class="dv">10</span>, penalty<span class="op">=</span><span class="st">"l1"</span>)</span>
<span id="cb5-4"><a href=""></a>ridge_logit <span class="op">=</span> LogisticRegressionCV(Cs<span class="op">=</span><span class="dv">10</span>, penalty<span class="op">=</span><span class="st">"l2"</span>)</span>
<span id="cb5-5"><a href=""></a>enet_logit <span class="op">=</span> LogisticRegressionCV(Cs<span class="op">=</span><span class="dv">10</span>, penalty<span class="op">=</span><span class="st">"elasticnet"</span>,  l1_ratios<span class="op">=</span><span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section><section id="generative-classification-models" class="title-slide slide level1 center" data-background-color="#447099"><h1>Generative classification models</h1>

</section><section id="definition" class="slide level2" style="color:#447099"><h2>Definition</h2>
<p>&nbsp;</p>
<ul>
<li><p>Logistic regression models directly the conditional mean of the response <span class="math inline">\(P(y=1|X)\)</span></p></li>
<li><p>Generative models involve modeling the distribution of the predictors separately for each one of the classes (that is, for each value of the response <span class="math inline">\(y\)</span>), that is <span class="math inline">\(P(X|y)\)</span></p></li>
<li>
<p>Then, <em>Bayes theorem</em> is applied to retrieve the conditional probability <span class="math inline">\(P(y|X)\)</span>, that is</p>
<p><span class="math display">\[P(y=k|X)=\frac{\pi_k P(X|y=k)}{\sum_j \pi_j P(X|y=k)}=\frac{\pi_k f_k(X)}{\sum_j \pi_j f_j(X)}\]</span></p>
</li>
<li><p>A unit is assigned to the class <span class="math inline">\(k\)</span> for which the posterior probability <span class="math inline">\(P(y=k|X)\)</span> is maximum</p></li>
<li>
<p>Why generative models?</p>
<ul>
<li>In certain circumstances (separation between classes is substantial, i.e.&nbsp;lack of overlap) logistic regression parameters are unstable</li>
<li>Accuracy gains when predictors are approximately normal and with small sample sizes</li>
<li>Naturally extend to more than two classes</li>
</ul>
</li>
</ul></section><section id="naive-bayes" class="slide level2" style="color:#447099"><h2>Naive Bayes</h2>
<p>&nbsp;</p>
<p>The trick to estimate generative models is how to tackle the estimation of <span class="math inline">\(f_k(\cdot)\)</span>. In the case of the <em>Naive Bayes</em> classifier a simplifying assumption is made: within the <span class="math inline">\(k\)</span>th class the <span class="math inline">\(p\)</span> predictors are independent. Then</p>
<p><span class="math display">\[f_k(X)=f_{k1}(x_1) \times f_{k2}(x_2) \times \ldots f_{kp}(x_p)\]</span> Implications</p>
<ul>
<li><p>The problem of estimating a <span class="math inline">\(p\)</span>-dimensional joint distribution is simplified to that of estimating marginal distributions (removing the need to estimate the joint distribution between the different predictors)</p></li>
<li><p>Though independence is hardly to sustain, <em>Naive Bayes</em> produces rather reasonable results</p></li>
</ul></section><section id="naive-bayes-decision-boundary" class="slide level2" style="color:#447099"><h2>Naive Bayes: decision boundary</h2>

<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-9-7.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section><section id="linear-discriminant-analysis" class="slide level2" style="color:#447099"><h2>Linear discriminant analysis</h2>
<p>&nbsp;</p>
<p><strong>Goal</strong>: find linear combinations of features that best separate different classes of data.</p>
<p><strong>Assumption</strong>: predictors <span class="math inline">\(X\)</span> are drawn from a multivariate Gaussian with class specific mean vector and common covariance matrix <span class="math inline">\(N(\mu_k,\Sigma)\)</span> (categorical variables that are to be treated as predictors are tough to accommodate).</p>
<ul>
<li><p>Using the mean and covariance of each class determines the optimal linear combination of features that maximizes the separation between classes while minimizing the overlap within each class.</p></li>
<li><p>LDA creates linear decision boundaries (lines or hyperplanes) to classify new data points based on their projected positions in the lower-dimensional space.</p></li>
</ul></section><section id="lda-decision-boundary" class="slide level2" style="color:#447099"><h2>LDA: decision boundary</h2>

<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-10-9.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section><section id="quadratic-discriminant-analysis" class="slide level2" style="color:#447099"><h2>Quadratic discriminant analysis</h2>
<p>&nbsp;</p>
<p>In <strong>QDA</strong> observations from each class are drawn from a Gaussian distribution BUT each class has its own covariance matrix, i.e.&nbsp;<span class="math inline">\(N(\mu_k,\Sigma_k)\)</span></p>
<ul>
<li><p>Once mean and covariance of each class are estimated QDA determines the optimal quadratic combination of features that maximizes the separation between classes while minimizing the overlap within each class (hence decision boundaries are no longer linear)</p></li>
<li><p>QDA requires estimating separate covariance matrix to each class: more flexibility hence more prone to overfitting.</p></li>
<li><p>In general, the larger the training dataset, the more allowance there is for flexible approaches (hence other things equal QDA’s requires larger training dataset)</p></li>
</ul></section><section id="qda-decision-boundary" class="slide level2" style="color:#447099"><h2>QDA: decision boundary</h2>

<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-11-11.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section></section><section><section id="predictive-performance-of-classifiers" class="title-slide slide level1 center" data-background-color="#447099"><h1>Predictive performance of classifiers</h1>

</section><section id="some-general-considerations" class="slide level2" style="color:#447099"><h2>Some general considerations</h2>
<p>&nbsp;</p>
<ul>
<li><p>All metrics of accuracy after training a classifier can be applied to both the training sample and the test sample.</p></li>
<li><p>Training sample metrics are generally expected to be better than those of the test sample: a model is likely to perform better on data it has seen before.</p></li>
<li><p>Good training sample performance metrics and poor test sample performance metrics are indicative of <strong>overfitting</strong>: the model “learns” the training data, including its noise and outliers, which negatively impacts its performance on new, unseen data (the test sample).</p></li>
</ul></section><section id="the-null-classifier" class="slide level2 scrollable" style="color:#447099"><h2>The null classifier</h2>
<p>&nbsp;</p>
<p>A null classifier is a simple baseline model used in classification tasks that doesn’t use any features to make predictions but resorts to the distribution of the target variable in the training data.</p>
<p>Most common types of null classifiers:</p>
<ol type="1">
<li><p>Majority class (also most frequent class) classifier: always predict the majority class from the training data.</p></li>
<li><p>Random (or stratified) classifier: predict with probability based on the class distribution in the training data.</p></li>
</ol>
<blockquote>
<p>The null classifier serves as a baseline to compare the performance of more complex models. If a model performs worse than the null classifier, it indicates that the model is not effectively capturing the patterns in the data.</p>
</blockquote>
</section><section class="slide level2">
<img data-src="pics/accuracy_classifier.webp" class="quarto-figure quarto-figure-center r-stretch"></section><section id="classification-errors" class="slide level2 scrollable" style="color:#447099"><h2>Classification errors</h2>
<p>&nbsp;</p>
<p>A binary classifier can make two types of errors:</p>
<ol type="1">
<li>
<strong>Type I error</strong> or false positive (<strong>FP</strong>): predict a positive outcome (1) for an instance that actually belongs to the negative class (0)</li>
<li>
<strong>Type II error</strong> or false negative (<strong>FN</strong>): predict a negative outcome (0) for an instance that actually belongs to the positive class (1)</li>
</ol>
<p>&nbsp;</p>
<p>These errors can be summarized in a <strong>confusion matrix</strong></p>
</section><section id="confusion-matrix" class="slide level2" style="color:#447099"><h2>Confusion matrix</h2>
<p>&nbsp;</p>
<div class="r-fit-text">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Predicted Negative (0)</th>
<th style="text-align: center;">Predicted Positive (1)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Actual Negative (0)</strong></td>
<td style="text-align: center;">True Negative (TN)</td>
<td style="text-align: center;"><span style="color: red;"> False Positive (FP) </span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Actual Positive (1)</strong></td>
<td style="text-align: center;"><span style="color: red;"> False Negative (FN) </span></td>
<td style="text-align: center;">True Positive (TP)</td>
</tr>
</tbody>
</table>
</div>
</section><section id="confusion-matrix-metrics-training-sample" class="slide level2" data-background-color="#447099"><h2>Confusion matrix &amp; metrics (training sample)</h2>
<p>&nbsp;</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              precision    recall  f1-score   support

           0   0.863049  0.837093  0.849873       399
           1   0.842615  0.867830  0.855037       401

    accuracy                       0.852500       800
   macro avg   0.852832  0.852462  0.852455       800
weighted avg   0.852807  0.852500  0.852461       800</code></pre>
</div>

</div>
<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-12-13.png" width="960" class="r-stretch"></section><section id="confusion-matrix-metrics-test-sample" class="slide level2" data-background-color="#447099"><h2>Confusion matrix &amp; metrics (test sample)</h2>
<p>&nbsp;</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              precision    recall  f1-score   support

           0   0.891304  0.820000  0.854167       100
           1   0.833333  0.900000  0.865385       100

    accuracy                       0.860000       200
   macro avg   0.862319  0.860000  0.859776       200
weighted avg   0.862319  0.860000  0.859776       200</code></pre>
</div>

</div>
<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-13-15.png" width="960" class="r-stretch"></section><section id="precision-and-accuracy-related-metrics" class="slide level2" style="color:#447099"><h2>Precision and accuracy-related metrics</h2>
<p>&nbsp;</p>
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 32%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th><strong>Metric</strong></th>
<th style="text-align: center;"><strong>Formula</strong></th>
<th><strong>Description</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Prevalence</strong></td>
<td style="text-align: center;"><span class="math display">\[\frac{TP + FN}{TP + TN + FP + FN}\]</span></td>
<td>Proportion of true positive instances among all instances.</td>
</tr>
<tr class="even">
<td><strong>Detection Rate</strong></td>
<td style="text-align: center;"><span class="math display">\[\frac{TP}{TP + TN + FP + FN}\]</span></td>
<td>Proportion of true positive instances among all instances.</td>
</tr>
<tr class="odd">
<td><strong>Accuracy</strong></td>
<td style="text-align: center;"><span class="math display">\[\frac{TP + TN}{TP + TN + FP + FN}\]</span></td>
<td>Proportion of correctly classified instances among all instances.</td>
</tr>
<tr class="even">
<td><strong>Precision</strong></td>
<td style="text-align: center;"><span class="math display">\[\frac{TP}{TP + FP}\]</span></td>
<td>Proportion of true positive instances among all instances predicted as positive.</td>
</tr>
<tr class="odd">
<td><strong>Sensitivity (Recall, TPR)</strong></td>
<td style="text-align: center;"><span class="math display">\[\frac{TP}{TP + FN}\]</span></td>
<td>Proportion of true positive instances among all positive instances.</td>
</tr>
<tr class="even">
<td><strong>Specificity</strong></td>
<td style="text-align: center;"><span class="math display">\[\frac{TN}{TN + FP}\]</span></td>
<td>Proportion of true negative instances among all negative instances.</td>
</tr>
<tr class="odd">
<td><strong>False Positive Rate (FPR)</strong></td>
<td style="text-align: center;"><span class="math display">\[1-\textrm{Specificity}=\frac{FP}{TN + FP}\]</span></td>
<td>Proportion of false positive instances among all negative instances.</td>
</tr>
<tr class="even">
<td><strong>F1 Score</strong></td>
<td style="text-align: center;"><span class="math display">\[2 \cdot \frac{\text{Precision} \cdot \text{Recall}}{\text{Precision} + \text{Recall}}\]</span></td>
<td>Harmonic mean of precision and recall.</td>
</tr>
<tr class="odd">
<td><strong>Error Rate</strong></td>
<td style="text-align: center;"><span class="math display">\[\frac{FP + FN}{TP + TN + FP + FN}\]</span></td>
<td>Proportion of incorrectly classified instances among all instances.</td>
</tr>
<tr class="even">
<td><strong>NIR</strong></td>
<td style="text-align: center;"><strong>Proportion of the most frequent class</strong></td>
<td>Non-information rate: proportion of the largest class in the dataset.</td>
</tr>
</tbody>
</table></section><section id="roc-curve" class="slide level2" style="color:#447099"><h2>ROC curve</h2>
<p>&nbsp;</p>
<ul>
<li><p>A <em>Receiver Operating Characteristic</em> (ROC) curve is a graphical plot that illustrates the performance of a binary classifier system as its discrimination threshold is varied. The ROC curve is created by plotting the true positive rate (TPR) against the false positive rate (FPR) at various threshold settings</p></li>
<li>
<p>Characteristics:</p>
<ul>
<li>True Positive Rate (TPR, also sensitivity or recall): proportion of actual positives correctly identified by the classifier.</li>
<li>False Positive Rate (FPR or 1-specificity): proportion of actual negatives incorrectly identified as positives by the classifier.</li>
<li>Diagonal Line: represents a random classifier with no discrimination ability (i.e., a 50-50 chance).</li>
<li>Area Under the Curve (AUC): The area under the ROC curve (AUC) quantifies the overall ability of the classifier to discriminate between positive and negative classes. An AUC of 1 indicates a perfect classifier, while an AUC of 0.5 indicates a classifier with no discrimination ability (diagonal line).</li>
</ul>
</li>
</ul>
<blockquote>
<p>The <strong>ROC (Receiver Operating Characteristic) Curve</strong> plots the True Positive Rate (Recall) against the False Positive Rate (1 - Specificity) for different threshold values. The area under the ROC curve (AUC) is a measure of the model’s ability to distinguish between the positive and negative classes.</p>
</blockquote>
</section><section id="roc-curve-training-sample" class="slide level2" data-background-color="#447099"><h2>ROC curve (training sample)</h2>

<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-14-17.png" width="960" class="r-stretch"></section><section id="roc-curve-training-sample-1" class="slide level2" data-background-color="#447099"><h2>ROC curve (training sample)</h2>

<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-15-19.png" class="quarto-figure quarto-figure-center r-stretch" width="576"></section><section id="roc-curve-test-sample" class="slide level2" data-background-color="#447099"><h2>ROC curve (test sample)</h2>

<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-16-21.png" width="960" class="r-stretch"></section><section id="roc-curve-test-sample-1" class="slide level2" data-background-color="#447099"><h2>ROC curve (test sample)</h2>

<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-17-23.png" class="quarto-figure quarto-figure-center r-stretch" width="576"></section><section id="uses-of-the-roc-curve" class="slide level2" style="color:#447099"><h2>Uses of the ROC curve</h2>
<p>&nbsp;</p>
<ul>
<li>
<p>Model comparison: ROC curves and AUC are used to compare the performance of different classifiers. The latter provides a metric of the overall performance of a binary classification model by quantifying the ability of the model to distinguish between positive and negative classes. The AUC value ranges from 0 to 1, where:</p>
<ul>
<li>AUC = 1: Perfect classifier</li>
<li>AUC = 0.5: Classifier with no discriminative power (equivalent to random guessing)</li>
<li>AUC &lt; 0.5: Classifier performing worse than random guessing</li>
</ul>
</li>
<li>
<p>Threshold selection: ROC curves help in selecting the optimal threshold for classification by balancing the trade-off between TPR and FPR.</p>
<ul>
<li>Choosing the threshold of the curve closest (euclidean distance) to the top-left corner of the plot - Assessing the costs associated with false positives and false negatives. By assigning different costs to these errors, the threshold that minimizes the overall cost can be determined</li>
</ul>
</li>
</ul>
<blockquote>
<p>AUC represents the probability that a randomly chosen positive instance is ranked higher than a randomly chosen negative instance</p>
</blockquote>
</section><section id="imbalanced-datasets" class="slide level2" style="color:#447099"><h2>Imbalanced datasets</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-3-1">ROC curve</a></li>
<li><a href="#tabset-3-2">Confusion matrix and metrics</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="03_classification_files/figure-revealjs/unnamed-chunk-18-25.png" class="quarto-figure quarto-figure-center" width="1920"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="03_classification_files/figure-revealjs/unnamed-chunk-18-26.png" class="quarto-figure quarto-figure-center" width="1920"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              precision    recall  f1-score   support

           0   0.926540  0.984887  0.954823       397
           1   0.647059  0.261905  0.372881        42

    accuracy                       0.915718       439
   macro avg   0.786800  0.623396  0.663852       439
weighted avg   0.899802  0.915718  0.899147       439</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure><p><img data-src="03_classification_files/figure-revealjs/unnamed-chunk-19-29.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="precision-recall-curve" class="slide level2" style="color:#447099"><h2>Precision-Recall Curve</h2>
<p><strong>Precision-Recall</strong> is a useful measure of success of prediction when the classes are very imbalanced. In information retrieval, precision is a measure of the fraction of relevant items among actually returned items while recall is a measure of the fraction of items that were returned among all items that should have been returned.</p>
<ul>
<li>
<strong>Precision</strong> (Positive Predictive Value): ratio of true positive predictions to the total number of positive predictions (both true positives and false positives). It answers the question: “Of all the instances predicted as positive, how many are actually positive?”</li>
</ul>
<p><span class="math display">\[\text{Precision} = \frac{\text{True Positives}}{\text{True Positives} + \text{False Positives}}\]</span></p>
<ul>
<li>
<strong>Recall</strong> (Sensitivity or True Positive Rate): ratio of true positive predictions to the total number of actual positives (true positives and false negatives). It answers the question: “Of all the actual positive instances, how many were correctly predicted as positive?”</li>
</ul>
<p><span class="math display">\[\text{Recall} = \frac{\text{True Positives}}{\text{True Positives} + \text{False Negatives}}\]</span></p>
<p>A <strong>Precision-Recall Curve</strong> plots precision (y-axis) against recall (x-axis) for different threshold values. It helps visualize the trade-off between precision and recall for different thresholds.</p>
</section><section id="precision-recall-curve-1" class="slide level2" style="color:#447099"><h2>Precision-Recall Curve</h2>

<img data-src="03_classification_files/figure-revealjs/unnamed-chunk-20-31.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section><section id="average-precision" class="slide level2" style="color:#447099"><h2>Average precision</h2>
<p>&nbsp;</p>
<p>The area under the curve is approximated through the average precision (<span class="math inline">\(AP\)</span>), which summarizes the precision-recall plot as the weighted mean of precisions achieved at each threshold, with the increase in recall from the previous threshold used as the weight: <span class="math display">\[\text{AP} = \sum_n (R_n - R_{n-1}) P_n\]</span></p>
</section></section>
</div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="03_classification_files/libs/revealjs/dist/reveal.js"></script><!-- reveal.js plugins --><script src="03_classification_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script><script src="03_classification_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script><script src="03_classification_files/libs/revealjs/plugin/reveal-menu/menu.js"></script><script src="03_classification_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script><script src="03_classification_files/libs/revealjs/plugin/quarto-support/support.js"></script><script src="03_classification_files/libs/revealjs/plugin/notes/notes.js"></script><script src="03_classification_files/libs/revealjs/plugin/search/search.js"></script><script src="03_classification_files/libs/revealjs/plugin/zoom/zoom.js"></script><script src="03_classification_files/libs/revealjs/plugin/math/math.js"></script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1920,

        height: 1080,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script><script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script><script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
          let selectedAnnoteEl;
          const selectorForAnnotation = ( cell, annotation) => {
            let cellAttr = 'data-code-cell="' + cell + '"';
            let lineAttr = 'data-code-annotation="' +  annotation + '"';
            const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
            return selector;
          }
          const selectCodeLines = (annoteEl) => {
            const doc = window.document;
            const targetCell = annoteEl.getAttribute("data-target-cell");
            const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
            const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            const lines = annoteSpan.getAttribute("data-code-lines").split(",");
            const lineIds = lines.map((line) => {
              return targetCell + "-" + line;
            })
            let top = null;
            let height = null;
            let parent = null;
            if (lineIds.length > 0) {
                //compute the position of the single el (top and bottom and make a div)
                const el = window.document.getElementById(lineIds[0]);
                top = el.offsetTop;
                height = el.offsetHeight;
                parent = el.parentElement.parentElement;
              if (lineIds.length > 1) {
                const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                height = bottom - top;
              }
              if (top !== null && height !== null && parent !== null) {
                // cook up a div (if necessary) and position it 
                let div = window.document.getElementById("code-annotation-line-highlight");
                if (div === null) {
                  div = window.document.createElement("div");
                  div.setAttribute("id", "code-annotation-line-highlight");
                  div.style.position = 'absolute';
                  parent.appendChild(div);
                }
                div.style.top = top - 2 + "px";
                div.style.height = height + 4 + "px";
                div.style.left = 0;
                let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                if (gutterDiv === null) {
                  gutterDiv = window.document.createElement("div");
                  gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                  gutterDiv.style.position = 'absolute';
                  const codeCell = window.document.getElementById(targetCell);
                  const gutter = codeCell.querySelector('.code-annotation-gutter');
                  gutter.appendChild(gutterDiv);
                }
                gutterDiv.style.top = top - 2 + "px";
                gutterDiv.style.height = height + 4 + "px";
              }
              selectedAnnoteEl = annoteEl;
            }
          };
          const unselectCodeLines = () => {
            const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
            elementsIds.forEach((elId) => {
              const div = window.document.getElementById(elId);
              if (div) {
                div.remove();
              }
            });
            selectedAnnoteEl = undefined;
          };
            // Handle positioning of the toggle
        window.addEventListener(
          "resize",
          throttle(() => {
            elRect = undefined;
            if (selectedAnnoteEl) {
              selectCodeLines(selectedAnnoteEl);
            }
          }, 10)
        );
        function throttle(fn, ms) {
        let throttle = false;
        let timer;
          return (...args) => {
            if(!throttle) { // first call gets through
                fn.apply(this, args);
                throttle = true;
            } else { // all the others get throttled
                if(timer) clearTimeout(timer); // cancel #2
                timer = setTimeout(() => {
                  fn.apply(this, args);
                  timer = throttle = false;
                }, ms);
            }
          };
        }
          const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
          for (let i=0; i<annoteTargets.length; i++) {
            const annoteTarget = annoteTargets[i];
            const targetCell = annoteTarget.getAttribute("data-target-cell");
            const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
            const contentFn = () => {
              const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              if (content) {
                const tipContent = content.cloneNode(true);
                tipContent.classList.add("code-annotation-tip-content");
                return tipContent.outerHTML;
              }
            }
            const config = {
              allowHTML: true,
              content: contentFn,
              onShow: (instance) => {
                selectCodeLines(instance.reference);
                instance.reference.classList.add('code-annotation-active');
                window.tippy.hideAll();
              },
              onHide: (instance) => {
                unselectCodeLines();
                instance.reference.classList.remove('code-annotation-active');
              },
              maxWidth: 300,
              delay: [50, 0],
              duration: [200, 0],
              offset: [5, 10],
              arrow: true,
              appendTo: function(el) {
                return el.parentElement.parentElement.parentElement;
              },
              interactive: true,
              interactiveBorder: 10,
              theme: 'light-border',
              placement: 'right',
              popperOptions: {
                modifiers: [
                {
                  name: 'flip',
                  options: {
                    flipVariations: false, // true by default
                    allowedAutoPlacements: ['right'],
                    fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                  },
                },
                {
                  name: 'preventOverflow',
                  options: {
                    mainAxis: false,
                    altAxis: false
                  }
                }
                ]        
              }      
            };
            window.tippy(annoteTarget, config); 
          }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>


</body></html>